name: Deploy to PyPI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to compare versions

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Set deployment context
        id: context
        run: |
          echo "environment=production" >> $GITHUB_OUTPUT
          echo "pypi_name=Production PyPI" >> $GITHUB_OUTPUT
          echo "pypi_url=https://pypi.org/project/readeck" >> $GITHUB_OUTPUT

      - name: Check version change
        id: version-check
        run: |
          # Get current version from pyproject.toml
          current_version=$(uv run python -c "
          import tomllib
          with open('pyproject.toml', 'rb') as f:
              data = tomllib.load(f)
          # Try to get version from project.version first, then from hatch.version
          if 'version' in data.get('project', {}):
              print(data['project']['version'])
          else:
              # For dynamic versioning, we need to build and check
              import subprocess
              result = subprocess.run(['uv', 'run', 'python', '-c', 'from importlib.metadata import version; print(version(\"readeck\"))'],
                                    capture_output=True, text=True, cwd='.')
              if result.returncode == 0:
                  print(result.stdout.strip())
              else:
                  # Fallback: extract from setuptools_scm or hatch
                  result = subprocess.run(['uv', 'run', 'python', 'setup.py', '--version'],
                                        capture_output=True, text=True, cwd='.')
                  if result.returncode == 0:
                      print(result.stdout.strip())
                  else:
                      print('0.0.0')  # fallback
          ")

          # Compare with previous commit
          git checkout HEAD~1 -- pyproject.toml
          comparison_version=$(uv run python -c "
          import tomllib
          with open('pyproject.toml', 'rb') as f:
              data = tomllib.load(f)
          if 'version' in data.get('project', {}):
              print(data['project']['version'])
          else:
              print('0.0.0')  # fallback
          ")
          echo "Comparison version (previous): $comparison_version"

          # Restore current pyproject.toml
          git checkout HEAD -- pyproject.toml

          echo "Current version: $current_version"
          echo "current_version=$current_version" >> $GITHUB_OUTPUT
          echo "comparison_version=$comparison_version" >> $GITHUB_OUTPUT

          if [ "$current_version" != "$comparison_version" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "Version has changed from $comparison_version to $current_version"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "Version has not changed"
          fi

      - name: Install twine
        if: steps.version-check.outputs.version_changed == 'true'
        run: uv tool install twine

      - name: Upload to Production PyPI
        if: steps.version-check.outputs.version_changed == 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          echo "Attempting to upload version ${{ steps.version-check.outputs.current_version }} to Production PyPI..."
          uv tool run twine upload dist/* --verbose
          echo "✅ Successfully uploaded version ${{ steps.version-check.outputs.current_version }} to Production PyPI"

      - name: Create GitHub Release
        if: steps.version-check.outputs.version_changed == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version-check.outputs.current_version }}
          release_name: Release v${{ steps.version-check.outputs.current_version }}
          body: |
            ## Changes
            Version ${{ steps.version-check.outputs.current_version }} has been released to PyPI.

            📦 Install with: `pip install readeck==${{ steps.version-check.outputs.current_version }}`
            🔗 PyPI: https://pypi.org/project/readeck/${{ steps.version-check.outputs.current_version }}/
          draft: false
          prerelease: false

      - name: Log success
        if: steps.version-check.outputs.version_changed == 'true'
        run: |
          echo "🚀 Package successfully uploaded to ${{ steps.context.outputs.pypi_name }}"
          echo "Version: ${{ steps.version-check.outputs.current_version }}"
          echo "URL: ${{ steps.context.outputs.pypi_url }}/${{ steps.version-check.outputs.current_version }}/"

      - name: Skip upload
        if: steps.version-check.outputs.version_changed == 'false'
        run: |
          echo "⏭️  Skipping PyPI upload - version has not changed"
          echo "Current version: ${{ steps.version-check.outputs.current_version }}"
          echo "Target: ${{ steps.context.outputs.pypi_name }}"

  deploy-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history to compare versions

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Check version change
        id: version-check
        run: |
          # Get current version from pyproject.toml
          current_version=$(uv run python -c "
          import tomllib
          with open('pyproject.toml', 'rb') as f:
              data = tomllib.load(f)
          if 'version' in data.get('project', {}):
              print(data['project']['version'])
          else:
              print('0.0.0')  # fallback
          ")

          # Compare with main branch
          git fetch origin main
          git checkout origin/main -- pyproject.toml
          comparison_version=$(uv run python -c "
          import tomllib
          with open('pyproject.toml', 'rb') as f:
              data = tomllib.load(f)
          if 'version' in data.get('project', {}):
              print(data['project']['version'])
          else:
              print('0.0.0')  # fallback
          ")
          echo "Comparison version (main): $comparison_version"

          # Restore current pyproject.toml
          git checkout HEAD -- pyproject.toml

          echo "Current version: $current_version"
          echo "current_version=$current_version" >> $GITHUB_OUTPUT
          echo "comparison_version=$comparison_version" >> $GITHUB_OUTPUT

          if [ "$current_version" != "$comparison_version" ]; then
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "Version has changed from $comparison_version to $current_version"
          else
            echo "version_changed=false" >> $GITHUB_OUTPUT
            echo "Version has not changed"
          fi

      - name: Install twine
        if: steps.version-check.outputs.version_changed == 'true'
        run: uv tool install twine

      - name: Upload to Test PyPI
        if: steps.version-check.outputs.version_changed == 'true'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        run: |
          echo "Attempting to upload version ${{ steps.version-check.outputs.current_version }} to Test PyPI..."

          # Try to upload, but don't fail if version already exists
          if ! uv tool run twine upload dist/* --verbose; then
            if uv tool run twine upload dist/* --verbose 2>&1 | grep -q "File already exists\|already exists"; then
              echo "⚠️  Version ${{ steps.version-check.outputs.current_version }} already exists on Test PyPI"
              echo "This is not an error - continuing with the workflow"
              exit 0
            else
              echo "❌ Failed to upload to Test PyPI for an unexpected reason"
              exit 1
            fi
          else
            echo "✅ Successfully uploaded version ${{ steps.version-check.outputs.current_version }} to Test PyPI"
          fi

      - name: Log success
        if: steps.version-check.outputs.version_changed == 'true'
        run: |
          echo "🚀 Package successfully uploaded to Test PyPI"
          echo "Version: ${{ steps.version-check.outputs.current_version }}"
          echo "URL: https://test.pypi.org/project/readeck/${{ steps.version-check.outputs.current_version }}/"

      - name: Skip upload
        if: steps.version-check.outputs.version_changed == 'false'
        run: |
          echo "⏭️  Skipping Test PyPI upload - version has not changed"
          echo "Current version: ${{ steps.version-check.outputs.current_version }}"
